// Registry tables the Valence JS client does not emit (DESIGN.md, "The Link page"):
// channel_id_ranges, the RFC-047 grid's class nibbles and experimental span, the
// nack_codes families and each code's meaning, all read from ../Valence's registry.yaml.
//   node tools/registry-tables.mjs           writes src/model/registry-tables.js
//   node tools/registry-tables.mjs --check   fails when the committed file is stale
// Hex is written unpadded: check-device-knowledge.mjs reads 0x0NNN as a channel id.
import { readFileSync, writeFileSync } from 'node:fs';

const YAML = new URL('../../Valence/spec/registry/registry.yaml', import.meta.url);
const OUT = new URL('../src/model/registry-tables.js', import.meta.url);
const text = readFileSync(YAML, 'utf8').replace(/\r\n/g, '\n');

const block = (name) => {
  const m = text.match(new RegExp('^' + name + ':\\n((?:(?:[ \\t]+.*)?\\n)*)', 'm'));
  if (!m) throw new Error('registry.yaml: no ' + name);
  return m[1].split('\n');
};
const entry = /^\s+(0x[0-9A-Fa-f]+)(?:-(0x[0-9A-Fa-f]+))?:\s*\{\s*name:\s*([\w-]+)(?:,\s*note:\s*"((?:[^"\\]|\\.)*)")?/;
const hex = (n) => '0x' + n.toString(16);

const ranges = [];
let grid = null, experimental = null;
for (const line of block('channel_id_ranges')) {
  const m = line.match(entry);
  if (!m) continue;
  const lo = parseInt(m[1], 16), hi = parseInt(m[2] || m[1], 16), note = m[4] || '';
  ranges.push({ lo, hi, name: m[3] });
  const cls = note.match(/class nibble ([^,]*)/);
  if (cls) grid = Object.fromEntries([...cls[1].matchAll(/(\d)=([A-Z]+)/g)].map((x) => [x[1], x[2]]));
  const ex = note.match(/(0x[0-9A-Fa-f]+)-(0x[0-9A-Fa-f]+) is reserved EXPERIMENTAL/);
  if (ex) experimental = { lo: parseInt(ex[1], 16), hi: parseInt(ex[2], 16) };
}
if (!grid || !experimental || ranges.length < 3) throw new Error('registry.yaml: channel_id_ranges changed shape');

// The note's first sentence: no RFC prefix, no parentheses, no code marks, and no
// ": aside" after a clause long enough to stand alone.
function meaning(note) {
  let s = note.replace(/`/g, '').replace(/^RFC-[\w.]+(?: \([^)]*\))?:\s*/, '');
  while (/\([^()]*\)/.test(s)) s = s.replace(/\s*\([^()]*\)/g, '');
  s = s.split(/(?<!\be\.g|\bi\.e)\.\s/)[0].replace(/\s+/g, ' ').trim().replace(/[.:]$/, '');
  if (s.indexOf(': ') >= 40) s = s.slice(0, s.indexOf(': '));
  return /^\S*_/.test(s) ? s : s.charAt(0).toUpperCase() + s.slice(1);
}
const family = {}, meanings = [];
for (const line of block('nack_codes')) {
  const f = line.match(/^\s+#\s*0x([0-9A-Fa-f]{2})xx\s*[—-]+\s*(.*)$/);
  if (f) family[parseInt(f[1], 16)] = { name: f[2].replace(/\s*\(.*\)\s*$/, '').trim(), distinct: /render these distinctly/.test(f[2]) };
  const m = line.match(entry);
  if (m) meanings.push([parseInt(m[1], 16), meaning(m[4] || '')]);
}

const out = `// GENERATED by tools/registry-tables.mjs from the Valence registry.yaml; never edit by hand.
// channel_id_ranges in id order; GRID_CLASS_NIBBLE and EXPERIMENTAL_RANGE from the
// device-defined range's note (RFC-047); NACK_FAMILY by the code's high byte; NACK_MEANING
// is each nack_codes note's first sentence.
export const CHANNEL_RANGES = [
${ranges.map((r) => `  { lo: ${hex(r.lo)}, hi: ${hex(r.hi)}, name: ${JSON.stringify(r.name)} },`).join('\n')}
];
export const GRID_CLASS_NIBBLE = ${JSON.stringify(grid)};
export const EXPERIMENTAL_RANGE = { lo: ${hex(experimental.lo)}, hi: ${hex(experimental.hi)} };
export const NACK_FAMILY = {
${Object.entries(family).map(([k, v]) => `  ${hex(+k)}: ${JSON.stringify(v)},`).join('\n')}
};
export const NACK_MEANING = {
${meanings.map(([c, s]) => `  ${hex(c)}: ${JSON.stringify(s)},`).join('\n')}
};
`;

if (process.argv.includes('--check')) {
  let have = '';
  try { have = readFileSync(OUT, 'utf8').replace(/\r\n/g, '\n'); } catch (e) { /* missing reads as stale */ }
  if (have !== out) { console.error('src/model/registry-tables.js is stale: run node tools/registry-tables.mjs'); process.exit(1); }
  console.log('registry-tables: current');
} else {
  writeFileSync(OUT, out);
  console.log('wrote src/model/registry-tables.js');
}
